<!DOCTYPE html>
<html lang="en">
<head>
   <script src="https://unpkg.com/react@18/umd/react.development.js" crossorigin></script>
   <script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js" crossorigin></script>
   <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
   <script type="text/babel" src="like_button.js"></script>
   <script defer="defer" src="./ui/build/static/js/main.479d104b.js"></script>
   <link href="./ui/build/static/css/main.073c9b0a.css" rel="stylesheet">
</head>